# Generated by Django 5.1.6 on 2025-02-16 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(default='ITC', max_length=200)),
                ('template', models.ImageField(upload_to='templates/')),
                ('csv_data', models.FileField(upload_to='data/')),
                ('roll_column', models.CharField(max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=200)),
                ('csv_column', models.CharField(max_length=200)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('font_size', models.IntegerField()),
                ('font_color', models.CharField(max_length=30)),
                ('font_family', models.CharField(max_length=30)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.certificate')),
            ],
        ),
    ]
